language: c
compiler: gcc
if: tag IS blank
script: /usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - autoconf
    - automake
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - wget
    - zip
    - rerun
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - BINTRAY_USER=stagrlee
  - BINTRAY_ORG=rerun
  - secure: YWsudd+a8hSyOTg+icVhZrfUUfXmPivsd6t3WEJknFxaV/P/9c0LiN/87u2uhWVVhRc/2gMGhhsVT34HE4HLAagO0obemLTdZaZQo+MhZEI/AGntC5C7h/qmgJIxJdunllsCkSxZSkZhtP7/FrQ1gz2+YeIQAaoh8N7bbHZHL+w=
  - secure: auYPHIqNVWS95blHFV6gB2SHH+IDsiJ9KdZRK3uP+3IkcAySsHPSWeuhYzg7bmqkDAn6ad0IsZRTkIMarK9tJDsEgMqksGM7lnTWvvUxEVCm4s7nB/M0uKhZCTtMRDRNaFaXkOF05ZIgl17Hjq7SWwekF31hYLWCYo6PLZen4Kk=
