dist: trusty
sudo: false
language: c
compiler: gcc
script: ./travis-ci.sh
notifications:
  irc:
    - "irc.freenode.org#rerun"
addons:
  apt:
    packages:
      - markdown
      - fakeroot
      - build-essential
      - devscripts
      - autoconf
      - automake
      - dh-make
      - libfile-fcntllock-perl
      - rpm
      - xmlstarlet
      - jq
      - wget
      - zip
      - rerun
    sources:
      - sourceline: 'deb https://dl.bintray.com/rerun/rerun-deb /'
env:
  global:
    - secure: "OKG83uTOFHfHbxrd8nN5JRVLGirXL/Kjto6UBi0wLi7GpC452nL0P87XQlVI\n+G27H0p38vbZ6WxHoLadu2dW+B4T/J5maPmSZPE4CZVbOORjAx/8fV3SYoBn\nj12ZNEgORkOSqVvnDBxJLDhzwZeVwiFsJcJ9H5S+3PmYIZrX4C0="
    - BINTRAY_USER=ahonor
    - BINTRAY_ORG=rerun
