#!/usr/bin/env bash

#/ command: bintray:package-version: "Retrieves versions for specified remote package."
#/ usage: rerun bintray:package-version  --org <>  --repo <>  --package <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ORG REPO PACKAGE

. $RERUN_MODULE_DIR/lib/functions.sh package-version || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

